required = [
  "github.com/golang/dep/cmd/dep",
  "github.com/golang/lint/golint",
  "k8s.io/repo-infra/kazel",
  "k8s.io/test-infra/prow/cmd/peribolos",
]

# Need override because release-1.12 and kubernetes-1.12.0 are not semver compliant
[[override]]
  name = "k8s.io/api"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"

# Need to override this to be compatible with k8s.io/client-go@v9.0.0
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v10.15.5"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
